name: swell-foop
version: git
summary: Clear the screen by removing groups of colored and shaped tiles
description: |
  Remove as many squares as possible from the board. Click on a group of
  squares of the same color to make them all disappear in one fell swoop,
  causing other squares to fall into place. It is not possible to remove a
  single square at a time. You get far more points for clearing a larger group
  of squares, and also for clearing the entire board.

  Swell Foop is always very quick to play, but you can make it somewhat longer
  by changing the board size.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: Swell Foop

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  swell-foop:
    interface: dbus
    bus: session
    name: org.gnome.SwellFoop

apps:
  swell-foop:
    command: desktop-launch snapcraft-preload swell-foop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.SwellFoop.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
# needed for clutter to work
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - gcc-multilib
      - g++-multilib

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  swell-foop:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: meson
    meson-parameters: [--prefix=/snap/swell-foop/current/usr]
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.SwellFoop$|Icon=${SNAP}/meta/gui/org.gnome.SwellFoop.png|g' data/org.gnome.SwellFoop.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/512x512/apps/org.gnome.SwellFoop.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/swell-foop/current/usr/share/applications/org.gnome.SwellFoop.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/swell-foop/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libclutter-gtk-1.0-dev
      - libgtk-3-dev
      - valac
    stage-packages:
      - libclutter-gtk-1.0-0
